apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-webserver
    service: webserver
  name: nginx-webserver
spec:
  containers:
  - image: nginx
    name: webserver
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /webserver
      name: webserver-storage
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: webserver-storage
    emptyDir:
      sizeLimit: 500Mi
